### ISSUE TITLE
Favourite button for Pokemon is blank on Android Slack app

### ISSUE THREAD

**Issue by juz501** [tdmalone/slackemon#11]
Maybe on mobile view, just use text?

**Comment by tdmalone** [comment]
Yeah I think text might be the way to go here. Emoji-only for this button works well on desktop because the buttons are horizontally aligned, but mobile vertically aligns them anyway.

EDIT: Worth noting that this probably isn't technically a Slack bug - I don't think they officially support emoji in button labels. I just used it because it had appeared to work anyway (except for custom emoji on iPhone app).

**Comment by tdmalone** [comment]
Fixed in v0.0.37.
